### ISSUE TITLE
"Failed to initialize pool: Feature is not supported" during Hikari initialization

### ISSUE THREAD

**Issue by konstantin-doncov** [aws/amazon-neptune-jdbc-driver#158]
As far as I understand, it is currently not possible to use the Neptune JDBC driver with [HikariCP](https://github.com/brettwooldridge/HikariCP) due to this error during `new HikariDataSource(config)`:
```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Feature is not supported.
Caused by: java.sql.SQLFeatureNotSupportedException: Feature is not supported.
	at software.aws.neptune.jdbc.utilities.SqlError.createSQLFeatureNotSupportedException(SqlError.java:167)
	at software.aws.neptune.jdbc.Connection.setReadOnly(Connection.java:341)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:409)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 6 more
```
Could you add support for HikariCP?

**Comment by jpines-vi** [comment]
I don't get that error using HikariDataSource with the JDBC connection to AWS Neptune. I do get a lot of problems with " apparent leak detections" and subsequent connection losses, though, causing me enough havoc to stop using HikariCP in my project. I would welcome any traction on this ticket just to know if HikariCP is or isn't supported.

**Comment by kenhuuu** [comment]
> Could you add support for HikariCP?

We'll take a look into this exception and get back to you.

> I don't get that error using HikariDataSource with the JDBC connection to AWS Neptune. I do get a lot of problems with " apparent leak detections" and subsequent connection losses, though, causing me enough havoc to stop using HikariCP in my project. I would welcome any traction on this ticket just to know if HikariCP is or isn't supported.

Do you mind sharing some more details about the configuration you are using with HikariCP? Is it just the defaults?
