### ISSUE TITLE
[BUG] Broken GROUP BY with renamed table

### ISSUE THREAD

**Issue by anchouls** [aws/amazon-neptune-jdbc-driver#174]
## Describe the bug

When creating an alias for a table other than the table name, GROUP BY stops working

- [x] **Have you validated that this is not currently reported in
    [SQL Support and Limitations](https://github.com/aws/amazon-neptune-jdbc-driver/blob/develop/sql-gremlin/README.asciidoc#sql-support-and-limitations)?**

## Steps to Reproduce

It was started by writing tests on the `develop` branch, commit [90feebb](https://github.com/aws/amazon-neptune-jdbc-driver/commit/90feebbb6b2ad1334c788c358e7cfb9c60830cbb)

**SQL query**

```
runJoinQueryTestResults("SELECT p.name FROM gremlin.person p " +
                "INNER JOIN gremlin.person p1 ON (p.friendsWith_OUT_ID = p1.friendsWith_IN_ID) " +
                "GROUP BY p.name",
        columns("name"),
        rows(r("Tom"), r("Patty"), r("Phil"), r("Susan")));
```
    
**Error**
```
Error: Unable to group table person.
java.sql.SQLException: Error: Unable to group table person.
	at org.twilmes.sql.gremlin.adapter.util.SqlGremlinError.create(SqlGremlinError.java:131)
	at org.twilmes.sql.gremlin.adapter.util.SqlGremlinError.create(SqlGremlinError.java:177)
	at org.twilmes.sql.gremlin.adapter.converter.ast.nodes.select.GremlinSqlSelectMulti.applyGroupBy(GremlinSqlSelectMulti.java:270)
	at org.twilmes.sql.gremlin.adapter.converter.ast.nodes.select.GremlinSqlSelectMulti.generateTraversal(GremlinSqlSelectMulti.java:215)
	at org.twilmes.sql.gremlin.adapter.converter.ast.nodes.select.GremlinSqlSelect.executeTraversal(GremlinSqlSelect.java:65)
	at org.twilmes.sql.gremlin.adapter.converter.SqlConverter.executeQuery(SqlConverter.java:92)
	at org.twilmes.sql.gremlin.adapter.GremlinSqlBaseTest.runJoinQueryTestResults(GremlinSqlBaseTest.java:118)
```

## Expected behavior

Specified in the test

## Environment

- OS: macOS Big Sur
- OS Version: 11.5.2
- openjdk 11.0.9.1 2020-11-04

**Comment by Cole-Greer** [comment]
Closing as PR was previously accepted
